# Generated by Django 6.0.1 on 2026-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.CharField(max_length=100),
        ),
    ]
